typedef struct {
    SDL_Renderer *renderer;
    SDL_Texture *imageTexture;
    SDL_Rect *Object;
    SDL_Rect *ImageObject;
    int Img_Rendering_XPosition;
    int Img_Rendering_YPosition;
    int scaledHeight;
    int scaledWidth;
    int CROP_RECT_WIDTH;
    int CROP_RECT_HEIGHT;
    int IMAGE_COUNT;
    int Character_Dest_Rect_Size;
    int FramesCount;
    int FrameLoop;
    char *name;
    int x;
    int y;
    int speed;
    int life;
} Personagem;

typedef struct{
    SDL_Renderer *renderer;
    SDL_Texture *imageTexture;
    SDL_Rect *Object;
    SDL_Rect *ImageObject;
    int Img_Rendering_XPosition;
    int Img_Rendering_YPosition;
    int scaledHeight;
    int scaledWidth;
    int CROP_RECT_WIDTH;
    int CROP_RECT_HEIGHT;
    int Character_Dest_Rect_Size;
} Objeto;